version: '3.8'

services:
  # Development version with hot reload
  nutrition-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: therapeutic-nutrition-app-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "3000:3000"  # Vite dev server
    environment:
      - NODE_ENV=development
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET:-dev-secret-key}
    volumes:
      - .:/app
      - /app/node_modules
      - dev-logs:/app/logs
    networks:
      - nutrition-dev-network
    depends_on:
      - postgres-dev
    command: npm run dev

  # PostgreSQL for development
  postgres-dev:
    image: postgres:15-alpine
    container_name: nutrition-postgres-dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PGDATABASE:-nutrition_app_dev}
      - POSTGRES_USER=${PGUSER:-nutrition_user}
      - POSTGRES_PASSWORD=${PGPASSWORD:-nutrition_password}
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - nutrition-dev-network
    ports:
      - "5433:5432"

volumes:
  postgres-dev-data:
    driver: local
  dev-logs:
    driver: local

networks:
  nutrition-dev-network:
    driver: bridge