version: '3.8'

services:
  # Main application for development
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nutrition-app-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - SESSION_SECRET=${SESSION_SECRET}
      - ENABLE_IMAGE_UPLOAD=${ENABLE_IMAGE_UPLOAD:-true}
      - ENABLE_VOICE_RECOGNITION=${ENABLE_VOICE_RECOGNITION:-true}
      - ENABLE_ACCESSIBILITY_FEATURES=${ENABLE_ACCESSIBILITY_FEATURES:-true}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-ar}
      - API_RATE_LIMIT=${API_RATE_LIMIT:-100}
      - UPLOAD_RATE_LIMIT=${UPLOAD_RATE_LIMIT:-10}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
    volumes:
      - .:/app
      - /app/node_modules
      - app-logs:/app/logs
    networks:
      - nutrition-network

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: nutrition-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${PGDATABASE:-nutrition_app_dev}
      - POSTGRES_USER=${PGUSER:-nutrition_user}
      - POSTGRES_PASSWORD=${PGPASSWORD:-nutrition_password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nutrition-network
    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local
  app-logs:
    driver: local

networks:
  nutrition-network:
    driver: bridge